---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
        - name: java-demo
          image: kubernetes.docker.internal/java-demo-app:1.2.9
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
