---
spec: 
  template:
    spec:
      containers:
      - name: java-demo
        image: kubernetes.docker.internal/java-demo-app:1.2.8
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
        - name: debug-port
          containerPort: 5005
          protocol: TCP

